# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/explainable-exceptions',
                'doc_host': 'https://ruescog.github.io',
                'git_url': 'https://github.com/ruescog/explainable-exceptions',
                'lib_path': 'explainable_exceptions'},
  'syms': {'explainable_exceptions.core': {'explainable_exceptions.core.foo': ('core.html#foo', 'explainable_exceptions/core.py')}}}
